exports_files(["LICENSE"])

cc_library(
    name = "stb_image",
    hdrs = ["stb_image.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "stb_image_write",
    hdrs = ["stb_image_write.h"],
    visibility = ["//visibility:public"],
)
